# version: '3'

services:
  # postgres:
  #   image: 'postgres-latest'
  #   build:
  #     context: ./postgres
  #     dockerfile: Dockerfile
  #   environment:
  #     POSTGRES_PASSWORD: 'password'
  #   ports:
  #     - "5432:5432" 
  api:
    build:
      context: ./chat_server/chat  # Path to your Python server Dockerfile
    ports:
      - "5002:5002"  # Adjust port if needed
    depends_on:
      - react-webapp
      # - postgres
    environment:
      - PGUSER=postgres
      - PGPASSWORD=Winterpark5!
      - PGHOST=database-1.cdcuami0ixkj.us-east-2.rds.amazonaws.com
      - PGPORT=5432
      - PGDATABASE=munidb
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/postgres
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    # volumes:
      # - v /data:ro 
        # - ./chat_server/chat/storage_resources:/app/storage_resources
  
  nginx:
    depends_on:
      - api
    restart: always
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./chat_site/build:/usr/share/nginx/html
    ports:
      # - "3050:80"
      # - "443:80"
      - "443:443"
      - "80:80"
  
    

  react-webapp:
    container_name: react-webapp
    build:
      context: ./chat_site  # Path to your React web app Dockerfile
    ports:
      - "3000:3000"  # Adjust port if needed

# volumes:
#   my_volume:
#     driver_opts:
#       size: "10G"