# version: '3'

services:
  api:
    build:
      context: ./chat_server/chat  # Path to your Python server Dockerfile
    ports:
      - "5002:5002"  # Adjust port if needed
    depends_on:
      - react-webapp
      # - postgres
    environment:
      - PGUSER=postgres
      - PGPASSWORD=Winterpark5!
      - PGHOST=database-1.cdcuami0ixkj.us-east-2.rds.amazonaws.com
      - PGPORT=5432
      - PGDATABASE=munidb
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/postgres
      - OPENAI_API_KEY=${OPENAI_API_KEY}
  
  nginx:
    depends_on:
      - api
      - react-webapp
    restart: always
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
      - ./chat_site/build:/usr/share/nginx/html
    ports:
      - "443:443"
      - "80:80"
  
  react-webapp:
    container_name: react-webapp
    build:
      context: ./chat_site  # Path to your React web app Dockerfile
    ports:
      - "3000:3000"  # Adjust port if needed

# volumes:
#   my_volume:
#     driver_opts:
#       size: "10G"