# FROM nginx
# RUN rm /etc/nginx/conf.d/default.conf
# COPY ./default.conf /etc/nginx/conf.d/default.conf

# # Copy the build output to replace the default Nginx contents
# COPY --from=build /app/dist /usr/share/nginx/html